<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="BO" failures="1" tests="4" name="Smoke Test" time="21.477" errors="0" timestamp="2023-03-02T13:37:55 EST">
  <testcase classname="com.exelenter.testcases.AddEmployeeTest" name="addEmployeeTest" time="3.49"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="2.276"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserEmptyPassword" time="0.105"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.712">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.exelenter.testcases.LoginTest.validUserInvalidPassword(LoginTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validUserInvalidPassword -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="0.0">
    <ignored/>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.0">
    <ignored/>
  </testcase> <!-- userLogin -->
</testsuite> <!-- Smoke Test -->
