<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="10" passed="0" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-03T05:46:42 EST" name="Excel Test Suite" finished-at="2023-03-03T05:48:50 EST" duration-ms="128226">
    <groups>
      <group name="excel">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- excel -->
      <group name="regression">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-03-03T05:46:42 EST" name="Excel test Cases" finished-at="2023-03-03T05:48:50 EST" duration-ms="128226">
      <class name="com.exelenter.testcases.AddEmployeeFromExcel">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:46:42 EST" name="setUp" finished-at="2023-03-03T05:46:44 EST" duration-ms="2684" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:46:44 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-03T05:47:07 EST" duration-ms="22463" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sophia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Patel]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[sophiapatel1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[tG^6pB=9uC,8]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:07 EST" name="tearDown" finished-at="2023-03-03T05:47:09 EST" duration-ms="2155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:09 EST" name="setUp" finished-at="2023-03-03T05:47:11 EST" duration-ms="1305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:11 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-03T05:47:32 EST" duration-ms="21381" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jackson]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chen]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[jacksonchen1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[xU;5tW<6wD+5]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:32 EST" name="tearDown" finished-at="2023-03-03T05:47:34 EST" duration-ms="2143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:34 EST" name="setUp" finished-at="2023-03-03T05:47:36 EST" duration-ms="1389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:36 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-03T05:47:57 EST" duration-ms="21421" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Isabella]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rodriguez]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[irodriguez]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[eG<2jU;3yD*4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:57 EST" name="tearDown" finished-at="2023-03-03T05:47:59 EST" duration-ms="2154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:47:59 EST" name="setUp" finished-at="2023-03-03T05:48:01 EST" duration-ms="1306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:48:01 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-03T05:48:23 EST" duration-ms="21926" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Caleb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Thomson]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[calebthomson1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[pF[6xI_9bR|9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:48:23 EST" name="tearDown" finished-at="2023-03-03T05:48:25 EST" duration-ms="2132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:48:25 EST" name="setUp" finished-at="2023-03-03T05:48:26 EST" duration-ms="1298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:48:26 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-03T05:48:48 EST" duration-ms="21407" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Zoe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Kim]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[zoekim1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[yR(5bF-5hY=1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@24aed80c]" started-at="2023-03-03T05:48:48 EST" name="tearDown" finished-at="2023-03-03T05:48:50 EST" duration-ms="2138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.testcases.AddEmployeeFromExcel -->
    </test> <!-- Excel test Cases -->
  </suite> <!-- Excel Test Suite -->
</testng-results>
